overrides:
  esbuild: ^0.28.0

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  unrs-resolver: true

minimumReleaseAge: 0
