catalog:
  '@tarojs/cli': ^4.0.9
  '@tarojs/components': ^4.0.9
  '@tarojs/helper': ^4.0.9
  '@tarojs/plugin-framework-vue3': ^4.0.9
  '@tarojs/plugin-html': ^4.0.9
  '@tarojs/plugin-platform-weapp': ^4.0.9
  '@tarojs/router': ^4.0.9
  '@tarojs/runtime': ^4.0.9
  '@tarojs/shared': ^4.0.9
  '@tarojs/taro': ^4.0.9
  '@tarojs/vite-runner': ^4.0.9
  babel-preset-taro: ^4.0.9
packages:
  - .
