packages:
  - .

catalog:
  '@babel/core': ^7.27.1
  '@babel/runtime': ^7.27.1
  '@ntnyq/eslint-config': ^4.3.0
  '@ntnyq/prettier-config': ^2.1.0
  '@nutui/icons-vue-taro': ^0.0.9
  '@nutui/nutui-taro': ^4.3.13
  '@tarojs/cli': ^4.1.1
  '@tarojs/components': ^4.1.1
  '@tarojs/helper': ^4.1.1
  '@tarojs/plugin-framework-vue3': ^4.1.1
  '@tarojs/plugin-html': ^4.1.1
  '@tarojs/plugin-platform-weapp': ^4.1.1
  '@tarojs/router': ^4.1.1
  '@tarojs/runtime': ^4.1.1
  '@tarojs/shared': ^4.1.1
  '@tarojs/taro': ^4.1.1
  '@tarojs/webpack5-runner': ^4.1.1
  '@types/webpack-env': ^1.18.8
  '@vue/babel-plugin-jsx': ^1.4.0
  '@vue/compiler-sfc': ^3.5.14
  babel-preset-taro: ^4.1.1
  bumpp: ^10.1.1
  dayjs: ^1.11.13
  eslint: ^9.27.0
  husky: ^9.1.7
  nano-staged: ^0.8.0
  pinia: ^3.0.2
  postcss: ^8.5.3
  prettier: ^3.5.3
  taro-define-config: ^0.10.7
  taro-plugin-pinia: ^1.0.0
  tsconfig-paths-webpack-plugin: ^4.2.0
  typescript: ^5.8.3
  unplugin-vue-components: ^28.5.0
  vue: ^3.5.14
  vue-loader: ^17.4.2
  vue-tsc: ^3.0.0-alpha.6
  webpack: ^5.99.8

overrides:
  esbuild: ^0.25.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tarojs/binding'
  - '@tarojs/cli'
  - core-js
  - core-js-pure
  - esbuild
  - unrs-resolver
